import 'package:flutter/cupertino.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class User {
  final String name;
  final int age;

  const User({
    required this.name,
    required this.age,
  });

  ///generated by "Dart Data Class" plugin
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is User &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          age == other.age);

  @override
  int get hashCode => name.hashCode ^ age.hashCode;

  @override
  String toString() {
    return 'User{ name: $name, age: $age,}';
  }

  User copyWith({
    String? name,
    int? age,
  }) {
    return User(
      name: name ?? this.name,
      age: age ?? this.age,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'age': age,
    };
  }

  factory User.fromMap(Map<String, dynamic> map) {
    return User(
      name: map['name'] as String,
      age: map['age'] as int,
    );
  }
}

//notifier
class UserNotifier extends StateNotifier<User> {
  // UserNotifier() : super(const User(name: '', age: 0));
  UserNotifier() : super(const User(name: '', age: 0)) {
    updateName('Initial Value'); //setting value on constructor
  }

  void updateName(String value) => state = state.copyWith(name: value);
}

//changeNotifier
class UserNotifierChange extends ChangeNotifier {
  User user = const User(name: '', age: 0);

  void updateName(String value) {
    user = user.copyWith(name: value);
    notifyListeners();
  }
}
